### ISSUE TITLE
Looking for CodeIgniter 3

### ISSUE THREAD

**Issue by ngekoding** [CodeIgniter/coding-standard#14]
Hi, I just found this coding-standard for CodeIgniter 4 only.
How about for CodeIgniter 3?

Thanks in advance

**Comment by kenjis** [comment]
Probably you can use this with CI3.
But if you don't like this style, you can use and configure php-cs-fixer directly or customize this package.
This package uses it.

**Comment by paulbalandan** [comment]
You may use this on your CI3 projects but there are rules changed between CI3 and CI4, such as tabs to spaces, alignment of `{ }`, etc. If you want to retain those styles, you can add [overrides](https://github.com/NexusPHP/cs-config?tab=readme-ov-file#overriding-rules-in-a-ruleset).

**Comment by ngekoding** [comment]
I thought there are already configured rules to apply to CodeIgniter 3.

I don't really know what must to configure to follow the [CodeIgniter 3 Style Guide](https://www.codeigniter.com/userguide3/general/styleguide.html).

Do you have any suggestions?

**Comment by paulbalandan** [comment]
You may reach out to the [forums](https://forum.codeigniter.com/) for help.

We use GitHub only to track bug reports. Thanks!

**Comment by kenjis** [comment]
You don't need to follow CodeIgniter 3 Style unless you send pull requests to CodeIginter3.
