### ISSUE TITLE
Adapt rules for PHP 8.1

### ISSUE THREAD

**Issue by paulbalandan** [CodeIgniter/coding-standard#15]
This change will target v4.5 once released.

**Comment by paulbalandan** [comment]
My question now is: should this branch off for a v2 release? @kenjis @MGatner

**Comment by kenjis** [comment]
No, it is not needed. Increment minor version number.
See https://medium.com/@sampart/semantic-versioning-when-you-change-the-required-programming-language-version-16a3a3555c95

**Comment by MGatner** [comment]
Agree with @kenjis: Compose will handle the language requirement and I don't see a need to maintain multiple styles branches with dedicated releases.

**Comment by paulbalandan** [comment]
I've created a new branch `1.8.x` to house all related changes pending release of `v4.5`.
